/* Generated By:JavaCC: Do not edit this line. DotParserConstants.java */
package org.coode.owlviz.util.graph.layout.dotlayoutengine.dotparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KWSTRICT = 5;
  /** RegularExpression Id. */
  int KWGRAPH = 6;
  /** RegularExpression Id. */
  int KWDIGRAPH = 7;
  /** RegularExpression Id. */
  int KWSUBGRAPH = 8;
  /** RegularExpression Id. */
  int KWNODE = 9;
  /** RegularExpression Id. */
  int KWEDGE = 10;
  /** RegularExpression Id. */
  int SQOPENPAR = 11;
  /** RegularExpression Id. */
  int SQCLOSEPAR = 12;
  /** RegularExpression Id. */
  int EQUALS = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int EDGEOP = 15;
  /** RegularExpression Id. */
  int ID = 16;
  /** RegularExpression Id. */
  int ALPHA = 17;
  /** RegularExpression Id. */
  int NUM = 18;
  /** RegularExpression Id. */
  int ALPHANUM = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"strict\"",
    "\"graph\"",
    "\"digraph\"",
    "\"subgraph\"",
    "\"node\"",
    "\"edge\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\"->\"",
    "<ID>",
    "<ALPHA>",
    "<NUM>",
    "<ALPHANUM>",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
