/* Generated By:JavaCC: Do not edit this line. DotParserConstants.java */
package uk.ac.man.cs.mig.util.graph.layout.dotlayoutengine.dotparser;

public interface DotParserConstants {

  int EOF = 0;
  int KWSTRICT = 5;
  int KWGRAPH = 6;
  int KWDIGRAPH = 7;
  int KWSUBGRAPH = 8;
  int KWNODE = 9;
  int KWEDGE = 10;
  int SQOPENPAR = 11;
  int SQCLOSEPAR = 12;
  int EQUALS = 13;
  int COMMA = 14;
  int EDGEOP = 15;
  int ID = 16;
  int ALPHA = 17;
  int NUM = 18;
  int ALPHANUM = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"strict\"",
    "\"graph\"",
    "\"digraph\"",
    "\"subgraph\"",
    "\"node\"",
    "\"edge\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\"->\"",
    "<ID>",
    "<ALPHA>",
    "<NUM>",
    "<ALPHANUM>",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
